# Generated by Django 4.0.6 on 2022-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validacao',
            name='justificativa',
            field=models.TextField(max_length=256),
        ),
    ]
