# Generated by Django 4.0.6 on 2022-08-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_validacao_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='arquivo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
